pipeline {
    agent any

    environment {
        ARTIFACTORY_ID = 'jfrog-artifactory-server'
        ARTIFACTORY_URL = credentials('artifactory-url')
        ARTIFACTORY_CREDENTIALS = credentials('artifactory-credentials')
    }

    stages {
        stage ('Clone') {
            steps {
                git branch: 'master', url: "https://github.com/yanhaeffner/congratulationsApp.git"
            }
        }
        
        stage ('Test') {
            steps{
                sh './gradlew test'
            }
        }
        
        stage ('Build') {
            steps{
                sh './gradlew build'
            }
        }

        stage ('Artifactory Deploy') {
            steps {
                rtServer (
                    id: 'env.ARTIFACTORY_ID,
                    url: env.ARTIFACTORY_URL,
                    username: env.ARTIFACTORY_CREDENTIALS_USR,
                    password: env.ARTIFACTORY_CREDENTIALS_PSW
                )

                rtUpload (
                    serverId: env.ARTIFACTORY_ID,
                    spec: '''{
                        "files": [
                            {
                                "pattern": "build/libs/congratulationsApp.jar",
                                "target": "gradle-release-local/congratulationsApp/"
                            } 
                        ]
                    }'''
                )
            }
        }
    }
}
