pipeline {
    agent any

    environment {
        DOCKERHUB_REPOSITORY = credentials('dockerhub-repository')
    }

    stages {
        stage ('Pull Docker Image') {
            steps {
		        sh 'docker pull "$DOCKERHUB_REPOSITORY":prod'
            }
        }
        
        stage ('Run or Start Container') {
            steps {
            	sh '''
        			if ! docker container ls -a | grep -Fq congratulationsApp 1>/dev/null; then
        			  echo "# Docker congratulationsApp container could not be found, running a new one"
        			  docker run -d -p 8282:8282 --name congratulationsApp "$DOCKERHUB_REPOSITORY":prod
        			else
        			  echo "# Docker congratulationsApp container found, starting it..."
        			  docker start congratulationsApp
        			fi
            	'''
            }
        }
    }
}
